services:
    postgres:
      image: postgres:13.3
      networks:
        - internal
      environment:
        POSTGRES_DB: ${DB_NAME:-app}
        POSTGRES_USER: ${DB_USER:?error}
        POSTGRES_PASSWORD: ${DB_PASSWORD:?error}
      ports:
        - "5432:5432"
      volumes:
        - ./volumes/db:/var/lib/postgresql/data

networks:
  internal:
    driver: bridge
