spring:
    application:
        name: wallet
    datasource:
        username: ${POSTGRES_USER:app}
        password: ${POSTGRES_PASSWORD:secret}
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:app}
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
              format_sql: true
        hibernate:
            ddl-auto: validate
        show-sql: false
    liquibase:
        enabled: true
    mvc:
      hiddenmethod:
        filter:
          enabled: true

logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure: ERROR
        root: info
        sql: info
                 
          
server:
    port: ${APP_PORT:8000}